

export   const algerianUniversities = [
  'Université Abderrahmane Mira de Béjaïa',
  'Université Abou Bekr Belkaïd de Tlemcen',
  'Université Abdelhamid Ibn Badis de Mostaganem',
  'Université Adrar Ahmed Draya',
  'Université Akli Mohand Oulhadj de Bouira',
  'Université Amar Telidji de Laghouat',
  "Université Badji Mokhtar d'Annaba",
  'Université Batna 1',
  'Université Batna 2',
  'Université Béchar Mohamed Tahri',
  'Université Biskra Dr. Mohamed Khider',
  "Université Boumerdès M'hamed Bougara",
  'Université Chlef El Hasnaoui',
  'Université Constantine 1 Mentouri',
  'Université Constantine 2 Abdelhamid Mehri',
  'Université Constantine 3 Salah Boubnider',
  'Université Djelfa Ziane Achour',
  'Université Dr. Tahar Moulay de Saida',
  'Université El Hadj Lakhdar de Batna',
  'Université Ferhat Abbas de Sétif 1',
  'Université Ferhat Abbas de Sétif 2',
  'Université Ghardaïa',
  'Université Hassiba Benbouali de Chlef',
  'Université Ibn Khaldoun de Tiaret',
  'Université Kasdi Merbah de Ouargla',
  "Université Mohamed Boudiaf d'Oum El Bouaghi",
  'Université Mohamed Lamine Debaghine de Sétif 3',
  'Université Mouloud Mammeri de Tizi-Ouzou',
  "Université M'sila Mohamed Bouzaréah",
  'Université Oran 1 Ahmed Ben Bella',
  'Université Oran 2 Mohamed Ben Ahmed',
  'Université Ouargla Kasdi Merbah',
  'Université Ouled Fayet',
  'Université Saâd Dahleb de Blida',
  'Université Sidi Bel Abbès Djillali Liabes',
  'Université Souk Ahras Mohammed Chérif Messaadia',
  'Université Tahar Moulay de Saïda',
  'Université Tlemcen Abou Bekr Belkaïd',
  'Université Tiaret Ibn Khaldoun',
  'Université Tizi-Ouzou Mouloud Mammeri',
  'Université Tlemcen Abou Bekr Belkaïd',
  'Université Tebessa Larbi Ben Mhidi',
  'Université de Béjaïa',
  'Université de Batna',
  'Université de Blida',
  'Université de Constantine',
  'Université de Djelfa',
  'Université de Ghardaïa',
  'Université de Laghouat',
  'Université de Mascara',
  'Université de Mostaganem',
  "Université de M'sila",
  'Université d’Oran',
  'Université de Ouargla',
  'Université de Saïda',
  'Université de Sétif',
  'Université de Sidi Bel Abbès',
  'Université de Souk Ahras',
  'Université de Tiaret',
  'Université de Tlemcen',
  'Université de Tizi-Ouzou',
  'Université de Tebessa',
];

export const faculties = [
  'Faculté des sciences',
  'Faculté des sciences humaines et sociales',
  'Faculté des lettres et des langues',
  'Faculté de droit',
  'Faculté de médecine',
  'Faculté de pharmacie',
  'Faculté de médecine dentaire',
  'Faculté de médecine vétérinaire',
  "Faculté des sciences de l'ingénieur",
  'Faculté des sciences économiques, commerciales et des sciences de gestion',
  "Faculté des sciences de l'éducation",
  'Faculté des sciences et techniques des activités physiques et sportives',
];

export const algerianSpecialities = [
  'Informatique',
  'Génie civil',
  'Génie électrique',
  'Génie mécanique',
  'Médecine',
  'Pharmacie',
  'Droit',
  'Économie',
  'Gestion',
  "Sciences de l'éducation",
  'Sciences humaines et sociales',
  'Sciences des langues',
  "Sciences de l'information et de la communication",
  'Arts et culture',
  'Mathématiques',
  'Physique',
  'Chimie',
  'Biologie',
  'Géologie',
  'Agronomie',
  'Architecture',
  'Urbanisme',
  'Aménagement du territoire',
  'Environnement',
  'Énergie',
  'Transport',
  'Tourisme',
  'Hôtellerie et restauration',
  'Service social',
  'Psychologie',
  'Sociologie',
  'Anthropologie',
  'Philosophie',
  'Histoire',
  'Géographie',
  'Langues étrangères',
  'Littérature',
  'Linguistique',
  'Journalisme',
  'Communication audiovisuelle',
  'Cinéma',
  'Théâtre',
  'Musique',
  'Danse',
  'Arts plastiques',
  'Design',
  "Architecture d'intérieur",
];


